### ISSUE TITLE
Access to trained Model

### ISSUE THREAD

**Issue by NirmalenduPrakash** [aniruddha343/Two-stream-Encoder-Decoder-Network-for-Image-Forensics#2]
Hi,

Thank you for the code.
The gdrive requires permission. Please provide the trained model.

Thanks,
Nirmal

**Comment by aniruddha343** [comment]
Hi, Please send me a request in google drive for downloading the weights. I will share the weights with you then.

**Comment by NirmalenduPrakash** [comment]
I did.

Thanks,
Nirmal

**Comment by NirmalenduPrakash** [comment]
Thank you so much!
