### ISSUE TITLE
Low F1

### ISSUE THREAD

**Issue by NirmalenduPrakash** [aniruddha343/Two-stream-Encoder-Decoder-Network-for-Image-Forensics#3]
Hi,

Why is there high AUC and low F1 on casiaV1?

Thanks,
Nirmal

**Comment by NirmalenduPrakash** [comment]
Also, It would be great if you could share model finetuned on casiav2. I get AUC of 0.62 using the weights shared on casiaV1.

Thanks,
Nirmal

**Comment by aniruddha343** [comment]
Hi, I can share the final trained model once my paper gets published. Also, if you have any non-coding-related questions about the paper, please drop me a mail in my email id mentioned in the paper. Please post only coding-related issues here as I don't frequently check the project.
